%% matlab transfer learning code
digitDatasetPath = fullfile('D:\data');
imds = imageDatastore(digitDatasetPath, ...
    'IncludeSubfolders',true,'LabelSource','foldernames');
[imdsTrain,imdsValidation,imdsTese] = splitEachLabel(imds,0.8,0.1,0.1,'randomized');

net = resnet18;
numClasses = numel(categories(imdsTrain.Labels));
lgraph = layerGraph(net);
newFCLayer = fullyConnectedLayer(numClasses,'Name','new_fc','WeightLearnRateFactor',10,'BiasLearnRateFactor',10);
lgraph = replaceLayer(lgraph,'fc1000',newFCLayer);
newClassLayer = classificationLayer('Name','new_classoutput');
lgraph = replaceLayer(lgraph,'ClassificationLayer_predictions',newClassLayer);
train_data_size = numel(imdsTrain.Labels);
options = trainingOptions('sgdm', ...
    'MiniBatchSize',30, ...
    'MaxEpochs',10, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'ValidationData',imdsValidation, ...
    'ValidationFrequency',50, ...
    'Verbose',false, ...
    'Plots','training-progress');
[trainedNet, process_data] = trainNetwork(imdsTrain,lgraph,options);

